import { Link, useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import StatCard from '../components/StatCard';
import { getPosts, getUsers, savePosts } from '../utils/storage';

/** Renders administrator-only local activity metrics and recent content controls. */
export default function AdminDashboard() {
  const navigate = useNavigate();
  const posts = [...getPosts()].sort((first, second) => new Date(second.createdAt) - new Date(first.createdAt));
  const users = getUsers();
  const admins = users.filter((user) => user.role === 'admin').length + 1;
  function deletePost(postId) { if (window.confirm('Delete this post?')) { savePosts(posts.filter((post) => post.id !== postId)); navigate('/admin'); } }
  return <div className="min-h-screen bg-slate-50"><Navbar /><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><section className="rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 p-8 text-white shadow-lg"><p className="text-sm font-bold uppercase tracking-[0.2em] text-violet-100">Administrator workspace</p><h1 className="mt-2 text-3xl font-extrabold">Welcome back, Administrator.</h1><p className="mt-3 max-w-2xl text-indigo-100">Monitor local activity, guide the writing community, and manage content from one focused view.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-lg bg-white px-4 py-2 font-medium text-indigo-700 shadow-sm hover:bg-indigo-50" to="/write">Write New Post</Link><Link className="rounded-lg border border-white/50 px-4 py-2 font-medium text-white hover:bg-white/10" to="/users">Manage Users</Link></div></section><section aria-label="Dashboard statistics" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard accent="bg-indigo-600" label="Total Posts" value={posts.length} /><StatCard accent="bg-violet-600" label="Total Users" value={users.length + 1} /><StatCard accent="bg-pink-500" label="Total Admins" value={admins} /><StatCard accent="bg-teal-500" label="Total users" value={users.filter((user) => user.role === 'user').length} /></section><section className="mt-10 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold text-slate-900">Recent Posts</h2><Link className="text-sm font-semibold text-indigo-600 hover:text-indigo-800" to="/blogs">View all</Link></div>{posts.length ? <ul className="mt-5 divide-y divide-slate-200">{posts.slice(0, 5).map((post) => <li className="flex flex-wrap items-center justify-between gap-3 py-4" key={post.id}><div><p className="font-semibold text-slate-900">{post.title}</p><p className="mt-1 text-sm text-slate-500">by {post.authorName}</p></div><div className="flex gap-2"><Link className="rounded-lg bg-white px-3 py-2 text-sm font-medium text-indigo-600 ring-1 ring-indigo-200 hover:bg-indigo-50" to={`/edit/${post.id}`}>Edit</Link><button className="rounded-lg bg-red-50 px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-100" onClick={() => deletePost(post.id)} type="button">Delete</button></div></li>)}</ul> : <p className="mt-5 rounded-xl bg-slate-50 p-5 text-slate-500">No posts to manage yet.</p>}</section></main></div>;
}
